spring.application.name=hustlehub

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/hustlehub
spring.datasource.username=postgres
spring.datasource.password=0244

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server Port
<<<<<<< HEAD
server.port=8080
=======
server.port=8081
>>>>>>> 53d7a84579d9d43e580542cb2354b524a70f8bf6
